theme: jekyll-theme-cayman
title: ## Growth Mindset
body: ### What Growth Mindset Means To Me...
Having a growth mindset to me means not giving up on yourself, and accepting that setbacks happen but ultimetly you learn and grow from them.
